# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            M.C. Shih
tagline:          'Quirky'
description:      'I share some stuff.'
url:              https://shihs.github.io/
baseurl:          /blog

author:
  name:           'Min-Chun Shih'
  url:            

paginate:         8

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/shihs/blog


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
