# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
# permalink: pretty
permalink: /:year/:month/:title.html

# Setup
title: M.C. Shih
tagline: "Quirky"
description: "Just for learning."
url: https://shihs.github.io
baseurl: /blog/
liker_id: shihs_tw

author:
  name: "Min-Chun Shih"
  url:

paginate: 8
paginate_path: "/page:num/"
encoding: UTF-8

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/shihs/blog

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
