# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: M.C. Shih
tagline: "Quirky"
description: "Just for learning."
url: https://shihs.github.io/
baseurl: /blog

author:
  name: "Min-Chun Shih"
  url:

paginate: 8

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/shihs/blog

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# Enter your Liker ID to enable LikeCoin button
liker_id: shihs_tw
