# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            M.C. Shih
tagline:          ''
description:      ''
url:              https://shihs.github.io/blog/
baseurl:          

author:
  name:           'MC Shih'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/shihs/blog


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
