# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            MinChun Shih
tagline:          ''
description:      ''
url:              https://shihs.github.io/
baseurl:          /blog/

author:
  name:           'MinChun Shih'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Isweet/isweet.github.io


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
